[package]
name = "roommd"
version = "0.2.0"
authors = ["Armin Schäfer"]
description = "Write room plans via markdown."
readme = "README.md"
edition = "2024"
categories = ["markdown"]
keywords = ["Markdown"]

[dependencies]
bevy = "0.16"
bevy_panorbit_camera = "0.26"
web-sys = { version = "0.3.77", features = ["Window", "Location"] }
urlencoding = "2.1.3"

[profile.dev]
opt-level = 0

[profile.dev.package."*"]
opt-level = 3
