[package]
name = "roommd"
version = "0.2.0"
authors = ["Armin Schäfer"]
description = "Write room plans via markdown."
repository = "https://github.com/772/roommd"
readme = "README.md"
license-file = "LICENSE"
edition = "2024"
categories = ["visualization"]
keywords = ["graphics"]

[dependencies]
bevy = "0.16"
bevy_panorbit_camera = "0.26"
web-sys = { version = "0.3.77", features = ["HtmlTextAreaElement"] }
urlencoding = "2.1.3"
license = "3.7.0"

[profile.dev]
opt-level = 0

[profile.dev.package."*"]
opt-level = 3
