[package]
name = "roommd"
version = "0.3.0"
authors = ["Armin Schäfer"]
description = "Creating building (wiring) diagrams should be as easy as writing markdown."
repository = "https://github.com/772/roommd"
readme = "README.md"
license-file = "LICENSE"
edition = "2024"
categories = ["visualization"]
keywords = ["graphics"]

[dependencies]
bevy = "0.16"
bevy_panorbit_camera = "0.26"
web-sys = { version = "0.3.77", features = ["HtmlTextAreaElement"] }

[profile.dev]
opt-level = 0

[profile.dev.package."*"]
opt-level = 3

[features]
dev = [
    "bevy/dynamic_linking",
]
